### ISSUE TITLE
Don't know how to make it work

### ISSUE THREAD

**Issue by chrisrosenkreuz23** [fenollp/vlc-sponsor-skip#1]
Hi, sorry to bother you, I really wanna make this work, it shows up under the View tab as "VLC Speed Controller" but when I click it, it does nothing. Also, it doesn't seem to skip any segments, all the sponsor bits just keep coming through. I used a custom addon for mozilla so that I click a link on youtube and "open in vlc" which just feeds the link to vlc and opens it. Do you have any insight into this?

**Comment by fenollp** [comment]
This is a work in progress and actually it's far from done.
The main issue being it's not clear how to fetch data through HTTPS in stdlib-only Lua.

**Comment by chrisrosenkreuz23** [comment]
oh okay. Thank you for the reply.

**Comment by fenollp** [comment]
https://github.com/mchangrh/sb-mirror/tree/775aabbe4dbb5f9273a37836cac5b25ea26be4b7#mirroring has some non-HTTPS links to the database which should greatly help implement the HTTP-querying part of this project (that I am not currently working on).

**Comment by chrisrosenkreuz23** [comment]
Thank you!
